# Generated by Django 6.0.3 on 2026-03-24 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SimulationRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lte_agents', models.IntegerField()),
                ('wifi_aps', models.IntegerField()),
                ('traffic', models.IntegerField()),
                ('algorithm', models.CharField(max_length=50)),
                ('throughput_lte', models.FloatField()),
                ('throughput_wifi', models.FloatField()),
                ('throughput_total', models.FloatField()),
                ('fairness', models.FloatField()),
                ('packet_loss_lte', models.FloatField()),
                ('packet_loss_wifi', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
