# Generated by Django 6.0.3 on 2026-03-31 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simulation', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='simulationrun',
            name='duty_cycle',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='simulationrun',
            name='reward',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
